spring:
  application:
    name: tx-user2
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
        #消费者重试机制
        retry:
          max-attempts: 3 #最大重试次数
          initial-interval: 1000 # 重试时间间隔
          enabled: true
        default-requeue-rejected: true
    host: 192.168.229.21
    username: guest
    password: guest
    virtual-host: /
    port: 5672
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///tx-rabbitmq?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root


server:
  port: 8090
